Area.create(name: '下北沢')
Area.create(name: '高円寺')
Area.create(name: '原宿')
Store.create(name: 'セカンドストリート', area_id: 1, outline: 'この店は有名なリユースショップです',  address: '東京都世田谷区北沢２丁目３０−１３ ファインコート下北沢 2F', postal_code: '155-0031')
Store.create(name: 'Encore', area_id: 2, outline: 'この店ではヨーロッパ各国のワークウェアを販売しています',  address: '東京都杉並区高円寺南３丁目５６−１−１１０', postal_code: '166-0003')
Store.create(name: 'Kinji', area_id: 3, outline: 'この店ではリーズナブルな洋服が多数販売されています',  address: '東京都渋谷区神宮前４丁目３１−１０ YMスクエア原宿B1F', postal_code: '150-0001')