Area.create(name: '下北沢')
Area.create(name: '高円寺')
Area.create(name: '原宿')
Store.create(name: 'セカンドストリート', area_id: 1)
Store.create(name: 'ニューヨークジョーエクスチェンジ', area_id: 2)
Store.create(name: 'Encore', area_id: 3)